sudo: false

language: android

env:
  global:
    # switch glibc to a memory conserving mode
    - MALLOC_ARENA_MAX=2
    # wait 5 minutes for adb to connect to emulator. Travis-ci cancels a
    # stalled build after 10 minutes, so this should be shorter than that so
    # there is time for the build to report the error.
    - ADB_INSTALL_TIMEOUT=5

jdk:
  - openjdk8

android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - build-tools-26.0.2
    - android-25
  licenses:
    # only approve the free software licenses
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'

script:
  # 'assemble' everything and run all checks that do not require a device/emulator
  - ./gradlew build
  - ./make-release-build

after_failure:
  - find * -name lint-results.xml | xargs cat
